---
title: "TidyTuesday Airbender"
author: "Jeff Matheson"
date: "2020-08-11"
output: 
  html_notebook:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

#  Required Packages
```{r packages}
library(tidytuesdayR)
library(tidyverse)
library(tvthemes)
library(skimr)
```

# Import Data
And have a look at some descriptive stats. Using package {skimr} for the first time. 
```{r import, message=FALSE, warning=FALSE}
tuesdata <- tidytuesdayR::tt_load('2020-08-11')
avatar <- tuesdata$avatar
scene_desc <- tuesdata$scene_description
```
```{r}
skimr::skim(avatar)
```

# A Few Summaries
## Scene-time: total scene frequency by character
```{r summary1, message=FALSE, warning=FALSE}
avatar %>% 
  group_by(book, character) %>% 
  summarize(n=n()) %>% 
  arrange(desc(n)) %>% 
  filter(character != "Scene Description") %>% 
  pivot_wider(id_cols = character, names_from = book, values_from = n) ->
char_sum
char_sum
```

## Epi-Freq: total episode frequency by character
```{r summary2, message=FALSE, warning=FALSE}
avatar %>% 
  group_by(book, character) %>% 
  summarize(n=n()) %>% 
  arrange(desc(n)) %>% 
  filter(character != "Scene Description") %>% 
  pivot_wider(id_cols = character, names_from = book, values_from = n) ->
char_sum
char_sum
```

## Are chapter imdb ratings correlated with frequency of a character in a scene?  
```{r char_ratings, message=FALSE, warning=FALSE, paged.print=TRUE}
char_imdb <- avatar %>% 
  filter(character %in% c("Ang", "Katara", "Sokka", "Zuko", "Toph", "Iroh", "Azula")) %>%
  mutate(BookandChapter = as.numeric(str_c(book_num, ".", chapter_num))) %>% 
  arrange(id) %>% 
  group_by(BookandChapter, character, imdb_rating) %>% 
  summarize(scene_count = n())
char_imdb

g <- char_imdb %>% 
  ggplot(mapping = aes(scene_count, imdb_rating, colour = character)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE) +
  labs(title = "Are Chapter IMDB Ratings Correlated with Character Scene Frequency?",
       colour = "Major Character") +
  xlab("Number of Scenes Within a Chapter That a Character Occurs In") +
  ylab("IMDB Rating") +
  theme_theLastAirbender()
g

```


table(avatar$)
